name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FLASK_APP: app.py
      FLASK_ENV: development

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências da aplicação
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar SonarScanner
        run: |
          npm install -g sonarqube-scanner

      - name: Analisar com SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          pip install coverage
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Subir a aplicação Flask em background
        run: |
          nohup python application.py &
          sleep 5
          
      - name: Rodar testes dentro de container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/tests:/tests \
            --workdir /tests \
            --network host \
            --entrypoint bash \
            websteredgar/robot-tests:latest \
            -c "robot tests.robot"




